### ISSUE TITLE
Template name

### ISSUE THREAD

**Issue by lanzone1** [yahoojp-marketing/gtm-template-ssa-conversion#1]
Hi,

When reviewing the template, we noticed that the template name is entirely in Japanese. Can you please include an English translation in the title similar to your [other templates](https://tagmanager.google.com/gallery/#/?filter=yahoojp-marketing)? 
Otherwise, it looks good.

Thanks.

**Comment by kenyamad** [comment]
Thank you for your comment. 

I will revise the template name similar to the other templates.

**Comment by kenyamad** [comment]
@lanzone1 
Hi,

Based on your comments, I have revised the template name. Please confirm it.
